[package]
name = "buptcan"
version = "0.2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
reqwest = {version = "0.11", features = ["blocking"]}
dialoguer = "0.8.0"
ctrlc = "3.1.9"